language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - pip install pycodestyle
  - pip install "aiohttp>=3,<4"
  - python setup.py install
script:
  - pytest -v
  - find . -name \*.py -exec pycodestyle {} +